pk = input().upper()
if pk[0]=="A": print("ace of ",end="")
elif pk[0]=="J": print("jack of ",end="")
elif pk[0]=="Q": print("queen of ",end="")
elif pk[0]=="K": print("king of ",end="")
elif len(pk)==3: print("10 of ",end="")
else: print(pk[0]+" of ",end="")
if pk[-1]=="S": print("spades")
elif pk[-1]=="H": print("hearts")
elif pk[-1]=="C": print("clubs")
else: print("diamonds")